name: USB Export Python Tests

on:
  push:
    paths: &python_usb_export_paths
      - 'tools/test_usb_export.py'
      - 'tools/usb_export.py'
      - 'tools/usb_common.py'
      - 'tools/requirements.txt'
      - '.github/workflows/python-usb-export.yml'
  pull_request:
    paths: *python_usb_export_paths

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/requirements.txt

      - name: Run tests
        run: |
          python3 tools/test_usb_export.py
